name: Notify team on new issue
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email via MailerSend API
        run: |
          curl -X POST https://api.mailersend.com/v1/email \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.MAILERSEND_API_TOKEN }}" \
          -d '{
            "from": {
              "email": "github-bot@trial-3rdeggml4he6k8n0.mlsend.com",
              "name": "GitHub Bot"
            },
            "to": [
              {
                "email": "robert.sekot@gepro.cz",
                "name": "Robert Sekot"
              }
            ],
            "cc": [
              {
                "email": "alena.cechova@gepro.cz",
                "name": "Alena Čechová"
              }
            ],
            "subject": "Nové issue v ${{ github.repository }}",
            "text": "🆕 Nové issue vytvořeno:\n\nRepo: ${{ github.repository }}\nČíslo: #${{ github.event.issue.number }}\nAutor: ${{ github.actor }}\nTitulek: ${{ github.event.issue.title }}\nURL: ${{ github.event.issue.html_url }}"
          }'
