name: Notify team on new issue
on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email via MailerSend API
        run: |
          curl -X POST https://api.mailersend.com/v1/email \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer mlsn.fb6d4f13feba2145f10d10d272bbd536a05850c19c1b6d5cb81b8e0eec9dabce" \
          -d '{
            "from": {
              "email": "github-bot@trial-3rdeggml4he6k8n0.mlsend.com",
              "name": "GitHub Bot"
            },
            "to": [
              {
                "email": "robert.sekot@gepro.cz",
                "name": "Robert Sekot"
              }
            ],
            "cc": [
              {
                "email": "alena.cechova@gepro.cz",
                "name": "Alena Čechová"
              }
            ],
            "subject": "Test email",
            "text": "Test zpráva z MailerSend API"
          }'
